/* Basic 2D stage for the classroom's Scratch projects. Uses the actual Scratch VM.
   For collision sensing and graphical effects, use the WebGL stage or Scratch. */
window.startBasicPlayer=async function(bytes,host,status){
 const {VM,Storage,JSZip}=Scaffolding.Packages;const vm=new VM();vm.setCompatibilityMode(true);vm.attachStorage(new Storage());
 const zip=await JSZip.loadAsync(bytes);const project=JSON.parse(await zip.file('project.json').async('string'));const urls=new Map();
 for(const t of project.targets)for(const c of t.costumes){const key=c.md5ext||c.assetId+'.'+c.dataFormat;if(!urls.has(key)&&zip.file(key)){const b=await zip.file(key).async('uint8array');urls.set(key,URL.createObjectURL(new Blob([b],{type:c.dataFormat==='svg'?'image/svg+xml':'image/'+c.dataFormat})));}}
 host.innerHTML='';host.style.cssText='position:relative;width:100%;height:calc(100vh - 128px);min-height:260px;background:#fff;overflow:hidden';
 const stage=document.createElement('div');stage.style.cssText='position:absolute;width:480px;height:360px;transform-origin:top left;overflow:hidden;background:white;';host.append(stage);
 const bg=document.createElement('img');bg.style.cssText='position:absolute;width:480px;height:360px;object-fit:fill';stage.append(bg);
 const monitors=document.createElement('div');monitors.style.cssText='position:absolute;z-index:20;left:8px;top:8px;display:flex;gap:8px;font:14px Tahoma';stage.append(monitors);
 const question=document.createElement('form');question.style.cssText='display:none;position:absolute;bottom:5px;left:10px;right:10px;background:white;border:2px solid #6654d6;border-radius:12px;padding:10px;z-index:30';
 const qlabel=document.createElement('label');qlabel.htmlFor='scratch-answer';const input=document.createElement('input');input.id='scratch-answer';input.setAttribute('aria-label','คำตอบ');input.style.cssText='font:18px Tahoma;width:70%;padding:6px';const send=document.createElement('button');send.textContent='ส่งคำตอบ';send.type='submit';question.append(qlabel,document.createElement('br'),input,send);stage.append(question);
 question.onsubmit=e=>{e.preventDefault();const a=input.value;question.style.display='none';vm.runtime.emit('ANSWER',a);};vm.runtime.on('QUESTION',q=>{question.style.display=q===null?'none':'block';qlabel.textContent=q||'';input.value='';if(q!==null)input.focus();});
 const sprites=new Map(),bubbles=new Map();vm.runtime.on('SAY',(target,type,text)=>{bubbles.set(target.id,text||'');});
 await vm.loadProject(bytes);let live=true;
 function draw(){if(!live)return;const scale=Math.min(host.clientWidth/480,host.clientHeight/360);stage.style.transform='scale('+scale+')';stage.style.left=(host.clientWidth-480*scale)/2+'px';stage.style.top=(host.clientHeight-360*scale)/2+'px';
  const st=vm.runtime.getTargetForStage();if(st){const c=st.getCostumes()[st.currentCostume];const src=urls.get(c?.md5ext||c?.assetId+'.'+c?.dataFormat);if(src&&bg.src!==src)bg.src=src;monitors.textContent='';for(const m of project.monitors||[])if(m.visible&&m.opcode==='data_variable'){const v=st.variables[m.id];if(v){const tag=document.createElement('span');tag.style.cssText='background:#ffb33e;border-radius:6px;padding:5px 10px';tag.textContent=v.name+': '+v.value;monitors.append(tag);}}}
  for(const t of vm.runtime.targets){if(t.isStage)continue;let entry=sprites.get(t.id);if(!entry){const box=document.createElement('div'),img=document.createElement('img'),speech=document.createElement('div');box.style.cssText='position:absolute;width:0;height:0';img.style.cssText='position:absolute;max-width:none';speech.style.cssText='position:absolute;bottom:72px;left:-90px;width:180px;border:1px solid #ccd2e2;border-radius:12px;background:white;padding:8px;text-align:center;font:12px Tahoma;z-index:15';box.append(img,speech);stage.append(box);entry={box,img,speech};sprites.set(t.id,entry);}entry.box.style.display=t.visible?'block':'none';entry.box.style.zIndex=String(t.getName()==='ผู้เล่น'?12:5);entry.box.style.left=(240+t.x)+'px';entry.box.style.top=(180-t.y)+'px';const c=t.getCostumes()[t.currentCostume];if(c){entry.img.alt=c.name||t.getName();const src=urls.get(c.md5ext||c.assetId+'.'+c.dataFormat);if(src&&entry.img.src!==src)entry.img.src=src;entry.img.style.left=-(c.rotationCenterX||0)+'px';entry.img.style.top=-(c.rotationCenterY||0)+'px';entry.img.style.transformOrigin=(c.rotationCenterX||0)+'px '+(c.rotationCenterY||0)+'px';entry.img.style.transform='scale('+t.size/100+')';}entry.speech.textContent=bubbles.get(t.id)||'';entry.speech.style.display=entry.speech.textContent?'block':'none';}
  requestAnimationFrame(draw);
 }draw();vm.start();status.textContent='โหมดภาพพื้นฐาน • พร้อมเล่น';const note=document.createElement('div');note.textContent='โหมดพื้นฐาน: หากใช้การชนหรือเอฟเฟกต์ ให้เปิดไฟล์ใน Scratch';note.style.cssText='display:none';
 window.addEventListener('pagehide',()=>{live=false;vm.stopAll();for(const u of urls.values())URL.revokeObjectURL(u);});
 return {greenFlag(){vm.greenFlag();},vm};
};
